apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
  namespace: monitoring
type: Opaque
stringData:
  # Replace with your real Discord webhook URL and apply manually.
  # This example file is tracked in Git on purpose, but should not be applied as-is.
  url: https://discord.com/api/webhooks/REPLACE_ME/REPLACE_ME
