apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: gateway=ghcr.io/checkmateit/checkmate-gateway
    argocd-image-updater.argoproj.io/gateway.update-strategy: newest-build
    argocd-image-updater.argoproj.io/gateway.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/gateway.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/gateway.allow-tags: "regexp:^[0-9]+$"
    argocd-image-updater.argoproj.io/gateway.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/checkMateit/checkmate-kubernetes.git
    targetRevision: HEAD
    path: charts/gateway
    helm:
      valueFiles:
        - ../../values/dev/gateway.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
