apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: user.user.svc.cluster.local
  namespace: user
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  # Retry budget is required for HTTP retries in Linkerd service profiles.
  retryBudget:
    ttl: 10s
    minRetriesPerSecond: 10
    retryRatio: 0.2
  routes:
    - name: get-users-me
      condition:
        method: GET
        pathRegex: "^/users/me$"
      isRetryable: false
      timeout: 5s
