apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  isCA: true
  commonName: root.linkerd.cluster.local
  secretName: linkerd-trust-anchor
  duration: 87600h0m0s
  renewBefore: 720h0m0s
  issuerRef:
    kind: Issuer
    name: linkerd-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor-issuer
  namespace: linkerd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  ca:
    secretName: linkerd-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  isCA: true
  commonName: identity.linkerd.cluster.local
  secretName: linkerd-identity-issuer
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  issuerRef:
    kind: Issuer
    name: linkerd-trust-anchor-issuer
  privateKey:
    algorithm: ECDSA
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: linkerd-identity-trust-roots
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  sources:
    - secret:
        name: linkerd-trust-anchor
        key: tls.crt
  target:
    configMap:
      key: ca-bundle.crt
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: linkerd
