apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-certs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: default
  source:
    repoURL: https://github.com/checkMateit/checkmate-kubernetes.git
    targetRevision: HEAD
    path: manifests/linkerd-certs
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
