apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: default
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-control-plane
    targetRevision: 1.16.11
    helm:
      releaseName: linkerd-control-plane
      values: |
        identityTrustAnchorsPEM: |
          -----BEGIN CERTIFICATE-----
          MIIDGjCCAgKgAwIBAgIUJ09ixvsOfH507qoKeqQzFZbEIwAwDQYJKoZIhvcNAQEL
          BQAwJTEjMCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjYw
          MjIzMTExMDQ1WhcNMzYwMjIxMTExMDQ1WjAlMSMwIQYDVQQDExpyb290Lmxpbmtl
          cmQuY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
          AK6NNio42JgPS3HQe5JzpKTZQFT3chptBVobiFktTeeGTwuuQ6MWwAu2dLKo4uV6
          aDgRQ48PXnzhq3gdBdKz5iF1FOUvkzLwr3Bpss4gJ819te5touKOGI7HpGBPEh7R
          YezlPvsr5vZucICuyjLhIXsl6265+RC2LMiRXGWJg6gt3XuqD4HT1ol0q/z1kH70
          Sl9YAjgLTMofdJjcXxeYKzVzQ/uo+Hj8VTQs2pwSfCv9Pb/dTwxSu3LJgyqnSRbG
          eMnFQAgmgRFYYWwKmY0uhnrFnWZ12k7SmGqqepgK41hF/hAT2+V0ritfMKAlRrjl
          P9iPzwFY3n/Txn+QLNi+S/kCAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1Ud
          EwEB/wQFMAMBAf8wHQYDVR0OBBYEFGOQ1YK81PPCfw/eNMIw5RIbbV3NMA0GCSqG
          SIb3DQEBCwUAA4IBAQAYEL3DkI0WLzTY/Jm6dAc6Vhdbd/ez3n9BzerOozfMcA6f
          UToDt1p2ep62kp0twYeP6Kuc+XbvFLfEG916sYtteBKUpxidva8v7e5Yr8MUtnj8
          g9bitc3IM7KBORVzN5SfoY7j7sAzCpZ9Pq4DB08ivUZhrnpVKd897kvIJ1mxLPZz
          Z+YHz40Li3KjbMALuJhWSf8CcF7kEsiKHpZmtzwAKRQ+C1W8isgG4fLc2rD1RvCR
          ujCmB0FYiti4A2r+nIpPtEVhiOZSI+25H9Gs3T86TvEeL9j2/BuM7/kV7FvPg9Qz
          ZiqHrNSdFGgc9AOiPE2nDGu6RfjU7V5uNALmoefu
          -----END CERTIFICATE-----
        identity:
          externalCA: true
          issuer:
            scheme: kubernetes.io/tls
            crtExpiry: 8760h0m0s
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
