apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
    - group: monitoring.coreos.com
      kind: Prometheus
      managedFieldsManagers:
        - prometheus-operator
    - group: monitoring.coreos.com
      kind: Alertmanager
      managedFieldsManagers:
        - prometheus-operator
  source:
    repoURL: https://github.com/checkMateit/checkmate-kubernetes.git
    targetRevision: HEAD
    path: charts/monitoring
    helm:
      valueFiles:
        - ../../values/dev/monitoring.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
