apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: store
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/checkMateit/checkmate-kubernetes.git
    targetRevision: HEAD
    path: charts/store
    helm:
      valueFiles:
        - ../../values/dev/store.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: store
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true