apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: user=ghcr.io/checkmate/checkmate-user
    argocd-image-updater.argoproj.io/user.update-strategy: newest-build
    argocd-image-updater.argoproj.io/user.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/user.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/checkMateit/checkmate-kubernetes.git
    targetRevision: HEAD
    path: charts/user
    helm:
      valueFiles:
        - ../../values/dev/user.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: user
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true